import type { Language } from "@/lib/i18n";

const en = {
  eyebrow: "Cadesca Events",
  title: "Apply as an official student club",
  subtitle: "Create or link an individual Cadesca account, verify your email, and submit your club for review.",
  accountSection: "Representative account",
  accountMode: "Account choice",
  newAccount: "Create account",
  linkAccount: "Link existing account",
  clubSection: "Club details",
  verificationSection: "University verification",
  university: "University",
  clubName: "Club name",
  clubSlug: "Preferred club link",
  officialEmail: "Official club email",
  representativeName: "Representative full name",
  representativeEmail: "Representative email",
  representativeUsername: "Cadesca username",
  password: "Password",
  confirmPassword: "Confirm password",
  description: "Club description",
  logo: "Club logo",
  instagram: "Official Instagram URL",
  website: "Website URL",
  universityPage: "Official university page URL",
  recognitionDocument: "University recognition document",
  contactPhone: "Contact phone (optional)",
  note: "Additional note (optional)",
  agreement: "I agree to the Cadesca club and event rules.",
  securityCheck: "Security check",
  securityLoadFailed: "Security verification failed to load. Refresh the page and try again.",
  sendCode: "Send verification code",
  resendCode: "Resend code",
  otp: "Six-digit verification code",
  submit: "Submit club application",
  submitting: "Submitting…",
  codeSent: "A code was sent to the representative email. It expires in 10 minutes.",
  passwordMismatch: "Passwords do not match.",
  passwordWeak: "Use at least 8 characters, including a letter, a number, and a special character.",
  usernameInvalid: "Use 3–30 lowercase letters, numbers, underscores or dots.",
  requiredFields: "Complete all required fields before continuing.",
  securityRequired: "Complete the security check first.",
  otpInvalid: "Enter the six-digit verification code.",
  otpExpired: "That verification code has expired. Request a new code.",
  otpTooMany: "Too many incorrect attempts. Request a new code and try again later.",
  uploadInvalid: "Upload a valid logo and recognition document.",
  sendFailed: "The verification code could not be sent. Try again shortly.",
  submitFailed: "The club application could not be submitted. Check the details and try again.",
  submitted: "Application submitted",
  submittedBody: "Your club is pending review. Publishing and attendee access remain unavailable until approval.",
  viewStatus: "View application status",
  futureLogin: "Future sign-ins use auth.cadesca.com with your username or email and password.",
  existingAccount: "Already use Cadesca? Enter your existing username and password. We will link the club without creating another identity.",
  statusTitle: "Club application status",
  statusSubtitle: "Review the latest decision and what your club can do next.",
  clubSummary: "Application details",
  submittedOn: "Submitted",
  representative: "Representative",
  decisionNote: "Review note",
  pendingBody: "Cadesca is checking the club and university materials. Event publishing and attendee access are locked during review.",
  clarificationBody: "The review team needs more information. Your club remains restricted until the application is updated and approved.",
  approvedBody: "Your club is approved. Active club roles can now use the club dashboard and submit events for moderation.",
  rejectedBody: "This application was not approved. Review the decision note before contacting support or submitting corrected information.",
  suspendedBody: "Club access is suspended. Event publishing, attendee data, finance tools, and scanning are unavailable.",
  archivedBody: "This application is archived and no longer active.",
  restrictedNotice: "Pending access never includes publishing, payments, attendee data, role management, or QR scanning.",
  editApplication: "Update application",
  editApplicationBody: "You can correct the club details or replace verification files while review is pending.",
  replacementFiles: "Replacement files (optional)",
  saveChanges: "Save changes",
  savingChanges: "Saving…",
  updateSuccess: "Application details updated.",
  updateFailed: "The application could not be updated. Reload the page and try again.",
  clarificationResponse: "Response to the review team",
  clarificationPlaceholder: "Explain the changes and answer the review team's question.",
  sendResponse: "Send response for review",
  sendingResponse: "Sending…",
  responseSent: "Your response was sent and the application returned to review.",
  universityUnavailable: "Club applications are temporarily unavailable because no supported university could be loaded.",
  noApplication: "No club application is linked to this account.",
  loginRequired: "Sign in to view your club application.",
  login: "Sign in at Cadesca Auth",
  newApplication: "Start an application",
  dashboard: "Open club dashboard",
  gatewayTitle: "Student Club",
  gatewayDescription: "View your application status. Club tools activate only after an administrator approves the club.",
  invitationsTitle: "Club role invitations",
  invitationsBody: "Accept an invitation to activate its permissions on your individual Cadesca account.",
  acceptInvitation: "Accept invitation",
  acceptingInvitation: "Accepting…",
  invitationAccepted: "Invitation accepted.",
  invitationFailed: "The invitation could not be accepted. Reload the page and try again.",
  invitationUnavailable: "This invitation is no longer active. Reload the page to see your current access.",
  invitationSessionExpired: "Your session expired. Sign in again, then accept the invitation.",
  roleClubOwner: "Club owner",
  roleEventOrganizer: "Event organizer",
  roleFinanceManager: "Finance manager",
  roleDoorScanner: "Door scanner",
  pending_review: "Pending review",
  clarification_requested: "More information requested",
  approved: "Approved",
  rejected: "Rejected",
  suspended: "Suspended",
  archived: "Archived"
} as const;

type ClubCopyKey = keyof typeof en;
type ClubCopy = Record<ClubCopyKey, string>;

const az: ClubCopy = {
  ...en,
  eyebrow: "Cadesca Tədbirləri",
  title: "Rəsmi tələbə klubu kimi müraciət et",
  subtitle: "Şəxsi Cadesca hesabını yarat və ya qoş, e-poçtunu təsdiqlə və klubu yoxlamaya göndər.",
  accountSection: "Nümayəndə hesabı",
  accountMode: "Hesab seçimi",
  newAccount: "Hesab yarat",
  linkAccount: "Mövcud hesabı qoş",
  clubSection: "Klub məlumatları",
  verificationSection: "Universitet təsdiqi",
  university: "Universitet",
  clubName: "Klubun adı",
  clubSlug: "İstənilən klub linki",
  officialEmail: "Klubun rəsmi e-poçtu",
  representativeName: "Nümayəndənin tam adı",
  representativeEmail: "Nümayəndənin e-poçtu",
  representativeUsername: "Cadesca istifadəçi adı",
  password: "Şifrə",
  confirmPassword: "Şifrəni təsdiqlə",
  description: "Klub haqqında",
  logo: "Klub loqosu",
  instagram: "Rəsmi Instagram linki",
  website: "Veb-sayt linki",
  universityPage: "Universitetin rəsmi səhifəsi",
  recognitionDocument: "Universitet tanınma sənədi",
  contactPhone: "Əlaqə telefonu (istəyə bağlı)",
  note: "Əlavə qeyd (istəyə bağlı)",
  agreement: "Cadesca klub və tədbir qaydaları ilə razıyam.",
  securityCheck: "Təhlükəsizlik yoxlaması",
  securityLoadFailed: "Təhlükəsizlik yoxlaması yüklənmədi. Səhifəni yeniləyib təkrar cəhd et.",
  sendCode: "Təsdiq kodu göndər",
  resendCode: "Kodu yenidən göndər",
  otp: "Altı rəqəmli təsdiq kodu",
  submit: "Klub müraciətini göndər",
  submitting: "Göndərilir…",
  codeSent: "Kod nümayəndənin e-poçtuna göndərildi və 10 dəqiqə etibarlıdır.",
  passwordMismatch: "Şifrələr uyğun gəlmir.",
  passwordWeak: "Ən azı 8 simvol, bir hərf, bir rəqəm və xüsusi simvol istifadə et.",
  usernameInvalid: "3–30 kiçik hərf, rəqəm, alt xətt və ya nöqtə istifadə et.",
  requiredFields: "Davam etməzdən əvvəl tələb olunan sahələri doldur.",
  securityRequired: "Əvvəl təhlükəsizlik yoxlamasını tamamla.",
  otpInvalid: "Altı rəqəmli təsdiq kodunu daxil et.",
  otpExpired: "Təsdiq kodunun vaxtı bitib. Yeni kod istə.",
  otpTooMany: "Həddən çox səhv cəhd edilib. Yeni kod istə və bir az sonra yenidən cəhd et.",
  uploadInvalid: "Etibarlı loqo və tanınma sənədi yüklə.",
  sendFailed: "Təsdiq kodu göndərilmədi. Bir az sonra yenidən cəhd et.",
  submitFailed: "Klub müraciəti göndərilmədi. Məlumatları yoxlayıb yenidən cəhd et.",
  submitted: "Müraciət göndərildi",
  submittedBody: "Klub yoxlanılır. Təsdiqə qədər tədbir dərc etmək və iştirakçı məlumatlarına baxmaq mümkün deyil.",
  viewStatus: "Müraciətin statusuna bax",
  futureLogin: "Sonrakı girişlər auth.cadesca.com üzərindən istifadəçi adı və ya e-poçtla edilir.",
  existingAccount: "Cadesca hesabın varsa, mövcud istifadəçi adı və şifrəni daxil et. Yeni kimlik yaradılmayacaq.",
  statusTitle: "Klub müraciətinin statusu",
  statusSubtitle: "Son qərarı və klubun növbəti addımlarını yoxla.",
  clubSummary: "Müraciət məlumatları",
  submittedOn: "Göndərilib",
  representative: "Nümayəndə",
  decisionNote: "Yoxlama qeydi",
  pendingBody: "Cadesca klub və universitet sənədlərini yoxlayır. Yoxlama müddətində tədbir dərc etmək və iştirakçı məlumatlarına baxmaq bağlıdır.",
  clarificationBody: "Yoxlama komandası əlavə məlumat istəyir. Müraciət yenilənib təsdiqlənənədək klub məhdud qalır.",
  approvedBody: "Klub təsdiqlənib. Aktiv klub rolları paneldən istifadə edib tədbirləri moderasiyaya göndərə bilər.",
  rejectedBody: "Müraciət təsdiqlənməyib. Dəstəyə yazmazdan və ya məlumatları düzəltməzdən əvvəl qərar qeydini yoxla.",
  suspendedBody: "Klub girişi dayandırılıb. Tədbirlər, iştirakçı məlumatları, maliyyə alətləri və QR skanı bağlıdır.",
  archivedBody: "Bu müraciət arxivlənib və artıq aktiv deyil.",
  restrictedNotice: "Gözləyən giriş tədbir dərc etmə, ödəniş, iştirakçı məlumatı, rol idarəsi və QR skanı vermir.",
  editApplication: "Müraciəti yenilə",
  editApplicationBody: "Yoxlama davam edərkən klub məlumatlarını düzəldə və təsdiq fayllarını əvəz edə bilərsən.",
  replacementFiles: "Əvəzedici fayllar (istəyə bağlı)",
  saveChanges: "Dəyişiklikləri saxla",
  savingChanges: "Saxlanılır…",
  updateSuccess: "Müraciət məlumatları yeniləndi.",
  updateFailed: "Müraciət yenilənmədi. Səhifəni yeniləyib təkrar cəhd et.",
  clarificationResponse: "Yoxlama komandasına cavab",
  clarificationPlaceholder: "Dəyişiklikləri izah et və yoxlama komandasının sualını cavablandır.",
  sendResponse: "Cavabı yoxlamaya göndər",
  sendingResponse: "Göndərilir…",
  responseSent: "Cavab göndərildi və müraciət yenidən yoxlamaya qaytarıldı.",
  universityUnavailable: "Dəstəklənən universitet yüklənmədiyi üçün klub müraciətləri müvəqqəti əlçatan deyil.",
  noApplication: "Bu hesaba bağlı klub müraciəti yoxdur.",
  loginRequired: "Klub müraciətinə baxmaq üçün daxil ol.",
  login: "Cadesca Auth-a daxil ol",
  newApplication: "Yeni müraciət et",
  dashboard: "Klub panelini aç",
  gatewayTitle: "Tələbə klubu",
  gatewayDescription: "Müraciətin statusuna bax. Klub alətləri yalnız administrator təsdiqindən sonra aktivləşir.",
  invitationsTitle: "Klub rol dəvətləri",
  invitationsBody: "Fərdi Cadesca hesabında səlahiyyətləri aktivləşdirmək üçün dəvəti qəbul et.",
  acceptInvitation: "Dəvəti qəbul et",
  acceptingInvitation: "Qəbul edilir…",
  invitationAccepted: "Dəvət qəbul edildi.",
  invitationFailed: "Dəvət qəbul edilmədi. Səhifəni yeniləyib təkrar cəhd et.",
  invitationUnavailable: "Bu dəvət artıq aktiv deyil. Cari girişini görmək üçün səhifəni yenilə.",
  invitationSessionExpired: "Sessiyan bitib. Yenidən daxil ol, sonra dəvəti qəbul et.",
  roleClubOwner: "Klub sahibi",
  roleEventOrganizer: "Tədbir təşkilatçısı",
  roleFinanceManager: "Maliyyə meneceri",
  roleDoorScanner: "Giriş skaneri",
  pending_review: "Yoxlanılır",
  clarification_requested: "Əlavə məlumat tələb olunur",
  approved: "Təsdiqlənib",
  rejected: "Rədd edilib",
  suspended: "Dayandırılıb",
  archived: "Arxivlənib"
};

const tr: ClubCopy = {
  ...en,
  eyebrow: "Cadesca Etkinlikleri",
  title: "Resmî öğrenci kulübü olarak başvur",
  subtitle: "Kişisel Cadesca hesabını oluştur veya bağla, e-postanı doğrula ve kulübünü incelemeye gönder.",
  accountSection: "Temsilci hesabı",
  accountMode: "Hesap seçimi",
  newAccount: "Hesap oluştur",
  linkAccount: "Mevcut hesabı bağla",
  clubSection: "Kulüp bilgileri",
  verificationSection: "Üniversite doğrulaması",
  university: "Üniversite",
  clubName: "Kulüp adı",
  clubSlug: "Tercih edilen kulüp bağlantısı",
  officialEmail: "Resmî kulüp e-postası",
  representativeName: "Temsilcinin adı soyadı",
  representativeEmail: "Temsilci e-postası",
  representativeUsername: "Cadesca kullanıcı adı",
  password: "Şifre",
  confirmPassword: "Şifreyi doğrula",
  description: "Kulüp açıklaması",
  logo: "Kulüp logosu",
  instagram: "Resmî Instagram adresi",
  website: "Web sitesi",
  universityPage: "Resmî üniversite sayfası",
  recognitionDocument: "Üniversite tanınma belgesi",
  contactPhone: "İletişim telefonu (isteğe bağlı)",
  note: "Ek not (isteğe bağlı)",
  agreement: "Cadesca kulüp ve etkinlik kurallarını kabul ediyorum.",
  securityCheck: "Güvenlik kontrolü",
  securityLoadFailed: "Güvenlik doğrulaması yüklenemedi. Sayfayı yenileyip tekrar dene.",
  sendCode: "Doğrulama kodu gönder",
  resendCode: "Kodu yeniden gönder",
  otp: "Altı haneli doğrulama kodu",
  submit: "Kulüp başvurusunu gönder",
  submitting: "Gönderiliyor…",
  codeSent: "Kod temsilci e-postasına gönderildi ve 10 dakika geçerlidir.",
  passwordMismatch: "Şifreler eşleşmiyor.",
  passwordWeak: "En az 8 karakter, bir harf, bir sayı ve özel karakter kullan.",
  usernameInvalid: "3–30 küçük harf, sayı, alt çizgi veya nokta kullan.",
  requiredFields: "Devam etmeden önce zorunlu alanları doldur.",
  securityRequired: "Önce güvenlik kontrolünü tamamla.",
  otpInvalid: "Altı haneli doğrulama kodunu gir.",
  otpExpired: "Doğrulama kodunun süresi doldu. Yeni bir kod iste.",
  otpTooMany: "Çok fazla hatalı deneme yapıldı. Yeni kod isteyip daha sonra tekrar dene.",
  uploadInvalid: "Geçerli bir logo ve tanınma belgesi yükle.",
  sendFailed: "Doğrulama kodu gönderilemedi. Biraz sonra tekrar dene.",
  submitFailed: "Kulüp başvurusu gönderilemedi. Bilgileri kontrol edip tekrar dene.",
  submitted: "Başvuru gönderildi",
  submittedBody: "Kulübün inceleniyor. Onaylanana kadar etkinlik yayımlama ve katılımcı erişimi kapalıdır.",
  viewStatus: "Başvuru durumunu görüntüle",
  futureLogin: "Sonraki girişler auth.cadesca.com üzerinden kullanıcı adı veya e-posta ve şifreyle yapılır.",
  existingAccount: "Cadesca hesabın varsa mevcut kullanıcı adı ve şifreni gir. Yeni bir kimlik oluşturulmaz.",
  statusTitle: "Kulüp başvuru durumu",
  statusSubtitle: "Son kararı ve kulübünün sonraki adımlarını görüntüle.",
  clubSummary: "Başvuru bilgileri",
  submittedOn: "Gönderildi",
  representative: "Temsilci",
  decisionNote: "İnceleme notu",
  pendingBody: "Cadesca kulüp ve üniversite belgelerini inceliyor. İnceleme süresince etkinlik yayımlama ve katılımcı erişimi kapalıdır.",
  clarificationBody: "İnceleme ekibi ek bilgi istiyor. Başvuru güncellenip onaylanana kadar kulüp kısıtlı kalır.",
  approvedBody: "Kulübün onaylandı. Aktif kulüp rolleri paneli kullanabilir ve etkinlikleri moderasyona gönderebilir.",
  rejectedBody: "Başvuru onaylanmadı. Destekle iletişime geçmeden veya bilgileri düzeltmeden önce karar notunu incele.",
  suspendedBody: "Kulüp erişimi askıya alındı. Etkinlik yayımlama, katılımcı verileri, finans araçları ve QR tarama kullanılamaz.",
  archivedBody: "Bu başvuru arşivlendi ve artık aktif değil.",
  restrictedNotice: "Bekleyen erişim; yayımlama, ödeme, katılımcı verileri, rol yönetimi veya QR tarama yetkisi vermez.",
  editApplication: "Başvuruyu güncelle",
  editApplicationBody: "İnceleme sürerken kulüp bilgilerini düzeltebilir ve doğrulama dosyalarını değiştirebilirsin.",
  replacementFiles: "Yeni dosyalar (isteğe bağlı)",
  saveChanges: "Değişiklikleri kaydet",
  savingChanges: "Kaydediliyor…",
  updateSuccess: "Başvuru bilgileri güncellendi.",
  updateFailed: "Başvuru güncellenemedi. Sayfayı yenileyip tekrar dene.",
  clarificationResponse: "İnceleme ekibine yanıt",
  clarificationPlaceholder: "Yaptığın değişiklikleri açıkla ve inceleme ekibinin sorusunu yanıtla.",
  sendResponse: "Yanıtı incelemeye gönder",
  sendingResponse: "Gönderiliyor…",
  responseSent: "Yanıtın gönderildi ve başvuru yeniden incelemeye alındı.",
  universityUnavailable: "Desteklenen bir üniversite yüklenemediği için kulüp başvuruları geçici olarak kullanılamıyor.",
  noApplication: "Bu hesaba bağlı kulüp başvurusu yok.",
  loginRequired: "Kulüp başvurusunu görmek için giriş yap.",
  login: "Cadesca Auth ile giriş yap",
  newApplication: "Başvuru başlat",
  dashboard: "Kulüp panelini aç",
  gatewayTitle: "Öğrenci Kulübü",
  gatewayDescription: "Başvuru durumunu görüntüle. Kulüp araçları yalnızca yönetici onayından sonra etkinleşir.",
  invitationsTitle: "Kulüp rol davetleri",
  invitationsBody: "Yetkileri kişisel Cadesca hesabında etkinleştirmek için daveti kabul et.",
  acceptInvitation: "Daveti kabul et",
  acceptingInvitation: "Kabul ediliyor…",
  invitationAccepted: "Davet kabul edildi.",
  invitationFailed: "Davet kabul edilemedi. Sayfayı yenileyip tekrar dene.",
  invitationUnavailable: "Bu davet artık etkin değil. Güncel erişimini görmek için sayfayı yenile.",
  invitationSessionExpired: "Oturumun sona erdi. Yeniden giriş yapıp daveti kabul et.",
  roleClubOwner: "Kulüp sahibi",
  roleEventOrganizer: "Etkinlik organizatörü",
  roleFinanceManager: "Finans yöneticisi",
  roleDoorScanner: "Giriş tarayıcısı",
  pending_review: "İnceleniyor",
  clarification_requested: "Ek bilgi istendi",
  approved: "Onaylandı",
  rejected: "Reddedildi",
  suspended: "Askıya alındı",
  archived: "Arşivlendi"
};

const ru: ClubCopy = {
  ...en,
  eyebrow: "События Cadesca",
  title: "Подайте заявку от официального студенческого клуба",
  subtitle: "Создайте или привяжите личный аккаунт Cadesca, подтвердите почту и отправьте клуб на проверку.",
  accountSection: "Аккаунт представителя",
  accountMode: "Выбор аккаунта",
  newAccount: "Создать аккаунт",
  linkAccount: "Привязать аккаунт",
  clubSection: "Информация о клубе",
  verificationSection: "Подтверждение университетом",
  university: "Университет",
  clubName: "Название клуба",
  clubSlug: "Желаемая ссылка клуба",
  officialEmail: "Официальная почта клуба",
  representativeName: "ФИО представителя",
  representativeEmail: "Почта представителя",
  representativeUsername: "Имя пользователя Cadesca",
  password: "Пароль",
  confirmPassword: "Подтвердите пароль",
  description: "Описание клуба",
  logo: "Логотип клуба",
  instagram: "Официальный Instagram",
  website: "Сайт",
  universityPage: "Официальная страница университета",
  recognitionDocument: "Документ о признании университетом",
  contactPhone: "Телефон (необязательно)",
  note: "Дополнительная заметка (необязательно)",
  agreement: "Я принимаю правила Cadesca для клубов и событий.",
  securityCheck: "Проверка безопасности",
  securityLoadFailed: "Не удалось загрузить проверку безопасности. Обновите страницу и повторите попытку.",
  sendCode: "Отправить код",
  resendCode: "Отправить код снова",
  otp: "Шестизначный код",
  submit: "Отправить заявку клуба",
  submitting: "Отправка…",
  codeSent: "Код отправлен на почту представителя и действует 10 минут.",
  passwordMismatch: "Пароли не совпадают.",
  passwordWeak: "Используйте минимум 8 символов, букву, цифру и специальный знак.",
  usernameInvalid: "Используйте 3–30 строчных букв, цифр, подчёркиваний или точек.",
  requiredFields: "Заполните все обязательные поля.",
  securityRequired: "Сначала завершите проверку безопасности.",
  otpInvalid: "Введите шестизначный код.",
  otpExpired: "Срок действия кода истёк. Запросите новый код.",
  otpTooMany: "Слишком много неверных попыток. Запросите новый код и повторите позже.",
  uploadInvalid: "Загрузите корректный логотип и документ.",
  sendFailed: "Не удалось отправить код. Повторите попытку позже.",
  submitFailed: "Не удалось отправить заявку. Проверьте данные и повторите попытку.",
  submitted: "Заявка отправлена",
  submittedBody: "Клуб ожидает проверки. До одобрения публикация событий и доступ к участникам закрыты.",
  viewStatus: "Посмотреть статус заявки",
  futureLogin: "Следующие входы выполняются на auth.cadesca.com по имени пользователя или почте и паролю.",
  existingAccount: "Если у вас уже есть Cadesca, введите текущее имя пользователя и пароль. Новая учётная запись не создаётся.",
  statusTitle: "Статус заявки клуба",
  statusSubtitle: "Посмотрите последнее решение и доступные клубу дальнейшие действия.",
  clubSummary: "Данные заявки",
  submittedOn: "Отправлена",
  representative: "Представитель",
  decisionNote: "Комментарий проверки",
  pendingBody: "Cadesca проверяет материалы клуба и университета. Публикация событий и доступ к участникам закрыты на время проверки.",
  clarificationBody: "Команде проверки нужна дополнительная информация. Ограничения сохраняются до обновления и одобрения заявки.",
  approvedBody: "Клуб одобрен. Активные клубные роли могут открыть панель и отправлять события на модерацию.",
  rejectedBody: "Заявка не одобрена. Ознакомьтесь с комментарием перед обращением в поддержку или исправлением данных.",
  suspendedBody: "Доступ клуба приостановлен. Публикация, данные участников, финансы и QR-сканирование недоступны.",
  archivedBody: "Эта заявка архивирована и больше не активна.",
  restrictedNotice: "Ожидающий статус не даёт доступа к публикации, платежам, данным участников, ролям или QR-сканированию.",
  editApplication: "Обновить заявку",
  editApplicationBody: "Пока идёт проверка, можно исправить данные клуба или заменить подтверждающие файлы.",
  replacementFiles: "Новые файлы (необязательно)",
  saveChanges: "Сохранить изменения",
  savingChanges: "Сохранение…",
  updateSuccess: "Данные заявки обновлены.",
  updateFailed: "Не удалось обновить заявку. Перезагрузите страницу и повторите попытку.",
  clarificationResponse: "Ответ команде проверки",
  clarificationPlaceholder: "Опишите изменения и ответьте на вопрос команды проверки.",
  sendResponse: "Отправить ответ на проверку",
  sendingResponse: "Отправка…",
  responseSent: "Ответ отправлен, заявка снова ожидает проверки.",
  universityUnavailable: "Заявки клубов временно недоступны: не удалось загрузить поддерживаемые университеты.",
  noApplication: "К этому аккаунту не привязана заявка клуба.",
  loginRequired: "Войдите, чтобы посмотреть заявку клуба.",
  login: "Войти через Cadesca Auth",
  newApplication: "Начать заявку",
  dashboard: "Открыть панель клуба",
  gatewayTitle: "Студенческий клуб",
  gatewayDescription: "Просмотрите статус заявки. Инструменты клуба станут доступны только после одобрения администратором.",
  invitationsTitle: "Приглашения на роли клуба",
  invitationsBody: "Примите приглашение, чтобы активировать права в своём личном аккаунте Cadesca.",
  acceptInvitation: "Принять приглашение",
  acceptingInvitation: "Принятие…",
  invitationAccepted: "Приглашение принято.",
  invitationFailed: "Не удалось принять приглашение. Обновите страницу и повторите попытку.",
  invitationUnavailable: "Это приглашение больше не активно. Обновите страницу, чтобы увидеть текущий доступ.",
  invitationSessionExpired: "Сеанс истёк. Войдите снова, затем примите приглашение.",
  roleClubOwner: "Владелец клуба",
  roleEventOrganizer: "Организатор событий",
  roleFinanceManager: "Финансовый менеджер",
  roleDoorScanner: "Сканировщик входа",
  pending_review: "На проверке",
  clarification_requested: "Запрошена дополнительная информация",
  approved: "Одобрено",
  rejected: "Отклонено",
  suspended: "Приостановлено",
  archived: "В архиве"
};

const CLUB_COPY: Record<Language, ClubCopy> = { en, az, tr, ru };

export function clubCopy(language: Language, key: ClubCopyKey) {
  return CLUB_COPY[language]?.[key] || en[key];
}

export type { ClubCopyKey };
