import Link from "next/link";

import { EventsRouteError } from "@/components/events/EventPrimitives";
import { hasClubCapability } from "@/lib/clubs/permissions";
import { getCurrentClubDashboardBySlug } from "@/lib/server/events";

export const dynamic = "force-dynamic";

export default async function ManagedClubSettingsPage({ params }: { params: Promise<{ clubSlug: string }> }) {
  const { clubSlug } = await params;
  const dashboard = await getCurrentClubDashboardBySlug(clubSlug);
  if (!dashboard || !hasClubCapability(dashboard.roles, "club.settings.manage")) return <EventsRouteError error="club_access_denied" />;
  const isOwner = dashboard.roles.includes("club_owner");
  return <><header className="border-b border-black/15 pb-6"><p className="text-xs font-bold uppercase tracking-[0.15em] text-black/45">Workspace</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.045em]">Settings</h1><p className="mt-2 text-sm text-black/55">Club-level preferences and account controls.</p></header><div className="mt-6 grid gap-5 xl:grid-cols-[220px_minmax(0,1fr)]"><nav aria-label="Settings sections" className="space-y-1"><a href="#general" className="block min-h-11 rounded-xl bg-black px-3 py-3 text-sm font-bold text-white">General</a><a href="#permissions" className="block min-h-11 rounded-xl px-3 py-3 text-sm font-bold hover:bg-white">Permissions</a><a href="#notifications" className="block min-h-11 rounded-xl px-3 py-3 text-sm font-bold hover:bg-white">Notifications</a>{isOwner ? <a href="#danger" className="block min-h-11 rounded-xl px-3 py-3 text-sm font-bold text-red-700 hover:bg-red-50">Danger zone</a> : null}</nav><div className="space-y-5"><section id="general" className="scroll-mt-24 rounded-2xl border border-black/10 bg-white p-6"><h2 className="text-xl font-semibold">General</h2><p className="mt-2 text-sm leading-6 text-black/55">Public identity changes are managed from the Club profile area.</p><Link href={`/dashboard/${dashboard.club.slug}/profile`} className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-black px-4 text-sm font-bold">Open club profile</Link></section><section id="permissions" className="scroll-mt-24 rounded-2xl border border-black/10 bg-white p-6"><h2 className="text-xl font-semibold">Permissions</h2><p className="mt-2 text-sm leading-6 text-black/55">Team roles are capability-backed and enforced on every management request.</p>{hasClubCapability(dashboard.roles, "club.members.manage") ? <Link href={`/dashboard/${dashboard.club.slug}/team`} className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-black px-4 text-sm font-bold">Manage team</Link> : null}</section><section id="notifications" className="scroll-mt-24 rounded-2xl border border-black/10 bg-white p-6"><h2 className="text-xl font-semibold">Notifications</h2><p className="mt-2 text-sm leading-6 text-black/55">Cadesca sends meaningful updates for invitations, reservations, cancellations and moderation—not every minor edit.</p></section>{isOwner ? <section id="danger" className="scroll-mt-24 rounded-2xl border border-red-200 bg-white p-6"><h2 className="text-xl font-semibold text-red-800">Danger zone</h2><p className="mt-2 text-sm leading-6 text-black/55">Ownership transfer and club archival require a reviewed support workflow so an accidental click cannot remove the organization.</p></section> : null}</div></div></>;
}
